package model

var instSize = [256]Size16{
	OpcodeNop: 1,

	OpcodeRST0x00: 1,
	OpcodeRST0x08: 1,
	OpcodeRST0x10: 1,
	OpcodeRST0x18: 1,
	OpcodeRST0x20: 1,
	OpcodeRST0x28: 1,
	OpcodeRST0x30: 1,
	OpcodeRST0x38: 1,

	OpcodeLDHLSPe: 2,
	OpcodeLDSPHL:  1,

	OpcodeLDBCA: 1,
	OpcodeLDDEA: 1,

	OpcodeLDSPnn: 3,
	OpcodeLDHLnn: 3,
	OpcodeLDBCnn: 3,
	OpcodeLDDEnn: 3,
	OpcodeLDAnn:  3,

	OpcodeLDHLn: 2,

	OpcodeCALLnn:   3,
	OpcodeCALLZnn:  3,
	OpcodeCALLCnn:  3,
	OpcodeCALLNZnn: 3,
	OpcodeCALLNCnn: 3,
	OpcodeJPnn:     3,
	OpcodeJPCnn:    3,
	OpcodeJPNCnn:   3,
	OpcodeJPZnn:    3,
	OpcodeJPNZnn:   3,
	OpcodeJRe:      2,
	OpcodeJRNZe:    2,
	OpcodeJRZe:     2,
	OpcodeJRNCe:    2,
	OpcodeJRCe:     2,

	OpcodeLDADE:    1,
	OpcodeLDABC:    1,
	OpcodeLDAHL:    1,
	OpcodeLDAHLDec: 1,
	OpcodeLDAHLInc: 1,

	OpcodeLDAn: 2,
	OpcodeLDBn: 2,
	OpcodeLDCn: 2,
	OpcodeLDDn: 2,
	OpcodeLDEn: 2,
	OpcodeLDHn: 2,
	OpcodeLDLn: 2,

	OpcodeLDHnA: 2,
	OpcodeLDHAn: 2,
	OpcodeLDHAC: 2,

	OpcodeXORA:  1,
	OpcodeXORB:  1,
	OpcodeXORC:  1,
	OpcodeXORD:  1,
	OpcodeXORE:  1,
	OpcodeXORH:  1,
	OpcodeXORL:  1,
	OpcodeXORHL: 1,

	OpcodeORA:  1,
	OpcodeORB:  1,
	OpcodeORC:  1,
	OpcodeORD:  1,
	OpcodeORE:  1,
	OpcodeORH:  1,
	OpcodeORL:  1,
	OpcodeORHL: 1,

	OpcodeANDA:  1,
	OpcodeANDB:  1,
	OpcodeANDC:  1,
	OpcodeANDD:  1,
	OpcodeANDE:  1,
	OpcodeANDH:  1,
	OpcodeANDL:  1,
	OpcodeANDHL: 1,

	OpcodeLDHLA: 1,
	OpcodeLDHLB: 1,
	OpcodeLDHLC: 1,
	OpcodeLDHLD: 1,
	OpcodeLDHLE: 1,
	OpcodeLDHLH: 1,
	OpcodeLDHLL: 1,

	OpcodeLDHLADec: 1,
	OpcodeLDHLAInc: 1,

	OpcodeCB: 2,

	OpcodeLDHCA: 1,

	OpcodeUndefD3: 1,
	OpcodeUndefDB: 1,
	OpcodeUndefDD: 1,
	OpcodeUndefE3: 1,
	OpcodeUndefE4: 1,
	OpcodeUndefEB: 1,
	OpcodeUndefEC: 1,
	OpcodeUndefED: 1,
	OpcodeUndefF4: 1,
	OpcodeUndefFC: 1,
	OpcodeUndefFD: 1,

	OpcodeCPLaka2f: 1,
	OpcodeCCF:      1,
	OpcodeSCF:      1,
	OpcodeDAA:      1,
	OpcodeEI:       1,
	OpcodeDI:       1,

	OpcodeCPA:  1,
	OpcodeCPB:  1,
	OpcodeCPC:  1,
	OpcodeCPD:  1,
	OpcodeCPE:  1,
	OpcodeCPH:  1,
	OpcodeCPL:  1,
	OpcodeCPHL: 1,

	OpcodeSUBA:  1,
	OpcodeSUBB:  1,
	OpcodeSUBC:  1,
	OpcodeSUBD:  1,
	OpcodeSUBE:  1,
	OpcodeSUBH:  1,
	OpcodeSUBL:  1,
	OpcodeSUBHL: 1,

	OpcodeSBCA:  1,
	OpcodeSBCB:  1,
	OpcodeSBCC:  1,
	OpcodeSBCD:  1,
	OpcodeSBCE:  1,
	OpcodeSBCH:  1,
	OpcodeSBCL:  1,
	OpcodeSBCHL: 1,

	OpcodeADDA:   1,
	OpcodeADDB:   1,
	OpcodeADDC:   1,
	OpcodeADDD:   1,
	OpcodeADDE:   1,
	OpcodeADDH:   1,
	OpcodeADDL:   1,
	OpcodeADDHL:  1,
	OpcodeADDSPe: 2,

	OpcodeADCA:  1,
	OpcodeADCB:  1,
	OpcodeADCC:  1,
	OpcodeADCD:  1,
	OpcodeADCE:  1,
	OpcodeADCH:  1,
	OpcodeADCL:  1,
	OpcodeADCHL: 1,

	OpcodeINCA:     1,
	OpcodeINCB:     1,
	OpcodeINCC:     1,
	OpcodeINCD:     1,
	OpcodeINCE:     1,
	OpcodeINCH:     1,
	OpcodeINCL:     1,
	OpcodeINCHL:    1,
	OpcodeINCBC:    1,
	OpcodeINCDE:    1,
	OpcodeINCSP:    1,
	OpcodeINCHLInd: 1,

	OpcodeDECA:     1,
	OpcodeDECB:     1,
	OpcodeDECC:     1,
	OpcodeDECD:     1,
	OpcodeDECE:     1,
	OpcodeDECH:     1,
	OpcodeDECL:     1,
	OpcodeDECHL:    1,
	OpcodeDECBC:    1,
	OpcodeDECDE:    1,
	OpcodeDECSP:    1,
	OpcodeDECHLInd: 1,

	OpcodeADDHLBC: 1,
	OpcodeADDHLDE: 1,
	OpcodeADDHLHL: 1,
	OpcodeADDHLSP: 1,

	OpcodeLDAA:  1,
	OpcodeLDAB:  1,
	OpcodeLDAC:  1,
	OpcodeLDAD:  1,
	OpcodeLDAE:  1,
	OpcodeLDAH:  1,
	OpcodeLDAL:  1,
	OpcodeLDBA:  1,
	OpcodeLDBB:  1,
	OpcodeLDBC:  1,
	OpcodeLDBD:  1,
	OpcodeLDBE:  1,
	OpcodeLDBH:  1,
	OpcodeLDBL:  1,
	OpcodeLDBHL: 1,
	OpcodeLDCA:  1,
	OpcodeLDCB:  1,
	OpcodeLDCC:  1,
	OpcodeLDCD:  1,
	OpcodeLDCE:  1,
	OpcodeLDCH:  1,
	OpcodeLDCL:  1,
	OpcodeLDCHL: 1,
	OpcodeLDDA:  1,
	OpcodeLDDB:  1,
	OpcodeLDDC:  1,
	OpcodeLDDD:  1,
	OpcodeLDDE:  1,
	OpcodeLDDH:  1,
	OpcodeLDDL:  1,
	OpcodeLDDHL: 1,
	OpcodeLDEA:  1,
	OpcodeLDEB:  1,
	OpcodeLDEC:  1,
	OpcodeLDED:  1,
	OpcodeLDEE:  1,
	OpcodeLDEH:  1,
	OpcodeLDEL:  1,
	OpcodeLDEHL: 1,
	OpcodeLDHA:  1,
	OpcodeLDHB:  1,
	OpcodeLDHC:  1,
	OpcodeLDHD:  1,
	OpcodeLDHE:  1,
	OpcodeLDHH:  1,
	OpcodeLDHL:  1,
	OpcodeLDHHL: 1,
	OpcodeLDLA:  1,
	OpcodeLDLB:  1,
	OpcodeLDLC:  1,
	OpcodeLDLD:  1,
	OpcodeLDLE:  1,
	OpcodeLDLH:  1,
	OpcodeLDLL:  1,
	OpcodeLDLHL: 1,

	OpcodePOPBC:  1,
	OpcodePOPDE:  1,
	OpcodePOPHL:  1,
	OpcodePOPAF:  1,
	OpcodePUSHBC: 1,
	OpcodePUSHDE: 1,
	OpcodePUSHHL: 1,
	OpcodePUSHAF: 1,

	OpcodeRLA:   1,
	OpcodeRLCA:  1,
	OpcodeRRA:   1,
	OpcodeRRCA:  1,
	OpcodeRET:   1,
	OpcodeRETZ:  1,
	OpcodeRETNZ: 1,
	OpcodeRETC:  1,
	OpcodeRETNC: 1,
	OpcodeRETI:  1,

	OpcodeSTOP: 1,
	OpcodeHALT: 1,
	OpcodeJPHL: 1,

	OpcodeADDn: 2,
	OpcodeSUBn: 2,
	OpcodeANDn: 2,
	OpcodeORn:  2,
	OpcodeADCn: 2,
	OpcodeSBCn: 2,
	OpcodeXORn: 2,
	OpcodeCPn:  2,

	OpcodeLDnnA:  3,
	OpcodeLDnnSP: 3,
}
