// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"errors"
	"fmt"
)

const (
	CBTargetB CBTarget = iota
	CBTargetC
	CBTargetD
	CBTargetE
	CBTargetH
	CBTargetL
	CBTargetIndirectHL
	CBTargetA
)

var ErrInvalidCBTarget = errors.New("not a valid CBTarget")

const _CBTargetName = "BCDEHLIndirectHLA"

// CBTargetValues returns a list of the values for CBTarget
func CBTargetValues() []CBTarget {
	return []CBTarget{
		CBTargetB,
		CBTargetC,
		CBTargetD,
		CBTargetE,
		CBTargetH,
		CBTargetL,
		CBTargetIndirectHL,
		CBTargetA,
	}
}

var _CBTargetMap = map[CBTarget]string{
	CBTargetB:          _CBTargetName[0:1],
	CBTargetC:          _CBTargetName[1:2],
	CBTargetD:          _CBTargetName[2:3],
	CBTargetE:          _CBTargetName[3:4],
	CBTargetH:          _CBTargetName[4:5],
	CBTargetL:          _CBTargetName[5:6],
	CBTargetIndirectHL: _CBTargetName[6:16],
	CBTargetA:          _CBTargetName[16:17],
}

// String implements the Stringer interface.
func (x CBTarget) String() string {
	if str, ok := _CBTargetMap[x]; ok {
		return str
	}
	return fmt.Sprintf("CBTarget(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CBTarget) IsValid() bool {
	_, ok := _CBTargetMap[x]
	return ok
}

var _CBTargetValue = map[string]CBTarget{
	_CBTargetName[0:1]:   CBTargetB,
	_CBTargetName[1:2]:   CBTargetC,
	_CBTargetName[2:3]:   CBTargetD,
	_CBTargetName[3:4]:   CBTargetE,
	_CBTargetName[4:5]:   CBTargetH,
	_CBTargetName[5:6]:   CBTargetL,
	_CBTargetName[6:16]:  CBTargetIndirectHL,
	_CBTargetName[16:17]: CBTargetA,
}

// ParseCBTarget attempts to convert a string to a CBTarget.
func ParseCBTarget(name string) (CBTarget, error) {
	if x, ok := _CBTargetValue[name]; ok {
		return x, nil
	}
	return CBTarget(0), fmt.Errorf("%s is %w", name, ErrInvalidCBTarget)
}

// MarshalText implements the text marshaller method.
func (x CBTarget) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CBTarget) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCBTarget(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Set implements the Golang flag.Value interface func.
func (x *CBTarget) Set(val string) error {
	v, err := ParseCBTarget(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *CBTarget) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *CBTarget) Type() string {
	return "CBTarget"
}

const (
	OpcodeNop Opcode = iota
	OpcodeLDBCnn
	OpcodeINCBC Opcode = iota + 1
	OpcodeINCB
	OpcodeDECB
	OpcodeLDBn
	OpcodeRLCA
	OpcodeADDHLBC Opcode = iota + 2
	OpcodeLDABC
	OpcodeDECBC
	OpcodeINCC
	OpcodeDECC
	OpcodeLDCn
	OpcodeRRCA
	OpcodeLDDEnn Opcode = iota + 3
	OpcodeINCDE  Opcode = iota + 4
	OpcodeINCD
	OpcodeDECD
	OpcodeLDDn
	OpcodeRLA
	OpcodeJRe
	OpcodeADDHLDE
	OpcodeLDADE
	OpcodeDECDE
	OpcodeINCE
	OpcodeDECE
	OpcodeLDEn
	OpcodeRRA
	OpcodeJRNZe
	OpcodeLDHLnn
	OpcodeLDHLAInc
	OpcodeINCHL
	OpcodeINCH
	OpcodeDECH
	OpcodeLDHn
	OpcodeJRZe Opcode = iota + 5
	OpcodeADDHLHL
	OpcodeDECHL Opcode = iota + 6
	OpcodeINCL
	OpcodeDECL
	OpcodeLDLn
	OpcodeJRNCe Opcode = iota + 7
	OpcodeLDSPnn
	OpcodeLDHLADec
	OpcodeINCSP
	OpcodeJRCe Opcode = iota + 11
	OpcodeADDHLSP
	OpcodeDECSP Opcode = iota + 12
	OpcodeINCA
	OpcodeDECA
	OpcodeLDAn
	OpcodeLDBB Opcode = iota + 13
	OpcodeLDBC
	OpcodeLDBD
	OpcodeLDBE
	OpcodeLDBH
	OpcodeLDBL
	OpcodeLDBHL
	OpcodeLDBA
	OpcodeLDCB
	OpcodeLDCC
	OpcodeLDCD
	OpcodeLDCE
	OpcodeLDCH
	OpcodeLDCL
	OpcodeLDCHL
	OpcodeLDCA
	OpcodeLDDB
	OpcodeLDDC
	OpcodeLDDD
	OpcodeLDDE
	OpcodeLDDH
	OpcodeLDDL
	OpcodeLDDHL
	OpcodeLDDA
	OpcodeLDEB
	OpcodeLDEC
	OpcodeLDED
	OpcodeLDEE
	OpcodeLDEH
	OpcodeLDEL
	OpcodeLDEHL
	OpcodeLDEA
	OpcodeLDHB
	OpcodeLDHC
	OpcodeLDHD
	OpcodeLDHE
	OpcodeLDHH
	OpcodeLDHL
	OpcodeLDHHL
	OpcodeLDHA
	OpcodeLDLB
	OpcodeLDLC
	OpcodeLDLD
	OpcodeLDLE
	OpcodeLDLH
	OpcodeLDLL
	OpcodeLDLHL
	OpcodeLDLA
	OpcodeLDHLB
	OpcodeLDHLC
	OpcodeLDHLD
	OpcodeLDHLE
	OpcodeLDHLH
	OpcodeLDHLL
	OpcodeHALT
	OpcodeLDHLA
	OpcodeLDAB
	OpcodeLDAC
	OpcodeLDAD
	OpcodeLDAE
	OpcodeLDAH
	OpcodeLDAL
	OpcodeLDAHL
	OpcodeLDAA
	OpcodeADDB
	OpcodeADDC
	OpcodeADDD
	OpcodeADDE
	OpcodeADDH
	OpcodeADDL
	OpcodeADDHL
	OpcodeADDA
	OpcodeADCB
	OpcodeADCC
	OpcodeADCD
	OpcodeADCE
	OpcodeADCH
	OpcodeADCL
	OpcodeADCHL
	OpcodeADCA
	OpcodeSUBB
	OpcodeSUBC
	OpcodeSUBD
	OpcodeSUBE
	OpcodeSUBH
	OpcodeSUBL
	OpcodeSUBHL
	OpcodeSUBA
	OpcodeSBCB
	OpcodeSBCC
	OpcodeSBCD
	OpcodeSBCE
	OpcodeSBCH
	OpcodeSBCL
	OpcodeSBCHL
	OpcodeSBCA
	OpcodeANDB
	OpcodeANDC
	OpcodeANDD
	OpcodeANDE
	OpcodeANDH
	OpcodeANDL
	OpcodeANDHL
	OpcodeANDA
	OpcodeXORB
	OpcodeXORC
	OpcodeXORD
	OpcodeXORE
	OpcodeXORH
	OpcodeXORL
	OpcodeXORHL
	OpcodeXORA
	OpcodeORB
	OpcodeORC
	OpcodeORD
	OpcodeORE
	OpcodeORH
	OpcodeORL
	OpcodeORHL
	OpcodeORA
	OpcodeCPB
	OpcodeCPC
	OpcodeCPD
	OpcodeCPE
	OpcodeCPH
	OpcodeCPL
	OpcodeCPHL
	OpcodeCPA
	OpcodeRETNZ
	OpcodePOPBC
	OpcodeJPNZnn
	OpcodeJPnn
	OpcodePUSHBC Opcode = iota + 14
	OpcodeADDn
	OpcodeRETZ Opcode = iota + 15
	OpcodeRET
	OpcodeJPZnn
	OpcodeCB
	OpcodeCALLnn Opcode = iota + 16
	OpcodeADCn
	OpcodeRETNC Opcode = iota + 17
	OpcodeRETC  Opcode = iota + 24
	OpcodeRETI
	OpcodeJPCnn
	OpcodeJPNCnn Opcode = iota + 15
	OpcodeSUBn   Opcode = iota + 18
	OpcodeSBCn   Opcode = iota + 25
	OpcodeLDHnA  Opcode = iota + 26
	OpcodeLDHCA  Opcode = iota + 27
	OpcodeANDn   Opcode = iota + 30
	OpcodeLDnnA  Opcode = iota + 33
	OpcodeXORn   Opcode = iota + 36
	OpcodeLDHAn  Opcode = iota + 37
	OpcodeLDAnn  Opcode = iota + 46
	OpcodeDI     Opcode = iota + 38
	OpcodeORn    Opcode = iota + 40
	OpcodeEI     Opcode = iota + 44
	OpcodeCPn    Opcode = iota + 46
)

var ErrInvalidOpcode = errors.New("not a valid Opcode")

const _OpcodeName = "NopLDBCnnINCBCINCBDECBLDBnRLCAADDHLBCLDABCDECBCINCCDECCLDCnRRCALDDEnnINCDEINCDDECDLDDnRLAJReADDHLDELDADEDECDEINCEDECELDEnRRAJRNZeLDHLnnLDHLAIncINCHLINCHDECHLDHnJRZeADDHLHLDECHLINCLDECLLDLnJRNCeLDSPnnLDHLADecINCSPJRCeADDHLSPDECSPINCADECALDAnLDBBLDBCLDBDLDBELDBHLDBLLDBHLLDBALDCBLDCCLDCDLDCELDCHLDCLLDCHLLDCALDDBLDDCLDDDLDDELDDHLDDLLDDHLLDDALDEBLDECLDEDLDEELDEHLDELLDEHLLDEALDHBLDHCLDHDLDHELDHHLDHLLDHHLLDHALDLBLDLCLDLDLDLELDLHLDLLLDLHLLDLALDHLBLDHLCLDHLDLDHLELDHLHLDHLLHALTLDHLALDABLDACLDADLDAELDAHLDALLDAHLLDAAADDBADDCADDDADDEADDHADDLADDHLADDAADCBADCCADCDADCEADCHADCLADCHLADCASUBBSUBCSUBDSUBESUBHSUBLSUBHLSUBASBCBSBCCSBCDSBCESBCHSBCLSBCHLSBCAANDBANDCANDDANDEANDHANDLANDHLANDAXORBXORCXORDXOREXORHXORLXORHLXORAORBORCORDOREORHORLORHLORACPBCPCCPDCPECPHCPLCPHLCPARETNZPOPBCJPNZnnJPnnPUSHBCADDnRETZRETJPZnnCBCALLnnADCnRETNCRETCRETIJPCnnJPNCnnSUBnSBCnLDHnALDHCAANDnLDnnAXORnLDHAnLDAnnDIORnEICPn"

// OpcodeValues returns a list of the values for Opcode
func OpcodeValues() []Opcode {
	return []Opcode{
		OpcodeNop,
		OpcodeLDBCnn,
		OpcodeINCBC,
		OpcodeINCB,
		OpcodeDECB,
		OpcodeLDBn,
		OpcodeRLCA,
		OpcodeADDHLBC,
		OpcodeLDABC,
		OpcodeDECBC,
		OpcodeINCC,
		OpcodeDECC,
		OpcodeLDCn,
		OpcodeRRCA,
		OpcodeLDDEnn,
		OpcodeINCDE,
		OpcodeINCD,
		OpcodeDECD,
		OpcodeLDDn,
		OpcodeRLA,
		OpcodeJRe,
		OpcodeADDHLDE,
		OpcodeLDADE,
		OpcodeDECDE,
		OpcodeINCE,
		OpcodeDECE,
		OpcodeLDEn,
		OpcodeRRA,
		OpcodeJRNZe,
		OpcodeLDHLnn,
		OpcodeLDHLAInc,
		OpcodeINCHL,
		OpcodeINCH,
		OpcodeDECH,
		OpcodeLDHn,
		OpcodeJRZe,
		OpcodeADDHLHL,
		OpcodeDECHL,
		OpcodeINCL,
		OpcodeDECL,
		OpcodeLDLn,
		OpcodeJRNCe,
		OpcodeLDSPnn,
		OpcodeLDHLADec,
		OpcodeINCSP,
		OpcodeJRCe,
		OpcodeADDHLSP,
		OpcodeDECSP,
		OpcodeINCA,
		OpcodeDECA,
		OpcodeLDAn,
		OpcodeLDBB,
		OpcodeLDBC,
		OpcodeLDBD,
		OpcodeLDBE,
		OpcodeLDBH,
		OpcodeLDBL,
		OpcodeLDBHL,
		OpcodeLDBA,
		OpcodeLDCB,
		OpcodeLDCC,
		OpcodeLDCD,
		OpcodeLDCE,
		OpcodeLDCH,
		OpcodeLDCL,
		OpcodeLDCHL,
		OpcodeLDCA,
		OpcodeLDDB,
		OpcodeLDDC,
		OpcodeLDDD,
		OpcodeLDDE,
		OpcodeLDDH,
		OpcodeLDDL,
		OpcodeLDDHL,
		OpcodeLDDA,
		OpcodeLDEB,
		OpcodeLDEC,
		OpcodeLDED,
		OpcodeLDEE,
		OpcodeLDEH,
		OpcodeLDEL,
		OpcodeLDEHL,
		OpcodeLDEA,
		OpcodeLDHB,
		OpcodeLDHC,
		OpcodeLDHD,
		OpcodeLDHE,
		OpcodeLDHH,
		OpcodeLDHL,
		OpcodeLDHHL,
		OpcodeLDHA,
		OpcodeLDLB,
		OpcodeLDLC,
		OpcodeLDLD,
		OpcodeLDLE,
		OpcodeLDLH,
		OpcodeLDLL,
		OpcodeLDLHL,
		OpcodeLDLA,
		OpcodeLDHLB,
		OpcodeLDHLC,
		OpcodeLDHLD,
		OpcodeLDHLE,
		OpcodeLDHLH,
		OpcodeLDHLL,
		OpcodeHALT,
		OpcodeLDHLA,
		OpcodeLDAB,
		OpcodeLDAC,
		OpcodeLDAD,
		OpcodeLDAE,
		OpcodeLDAH,
		OpcodeLDAL,
		OpcodeLDAHL,
		OpcodeLDAA,
		OpcodeADDB,
		OpcodeADDC,
		OpcodeADDD,
		OpcodeADDE,
		OpcodeADDH,
		OpcodeADDL,
		OpcodeADDHL,
		OpcodeADDA,
		OpcodeADCB,
		OpcodeADCC,
		OpcodeADCD,
		OpcodeADCE,
		OpcodeADCH,
		OpcodeADCL,
		OpcodeADCHL,
		OpcodeADCA,
		OpcodeSUBB,
		OpcodeSUBC,
		OpcodeSUBD,
		OpcodeSUBE,
		OpcodeSUBH,
		OpcodeSUBL,
		OpcodeSUBHL,
		OpcodeSUBA,
		OpcodeSBCB,
		OpcodeSBCC,
		OpcodeSBCD,
		OpcodeSBCE,
		OpcodeSBCH,
		OpcodeSBCL,
		OpcodeSBCHL,
		OpcodeSBCA,
		OpcodeANDB,
		OpcodeANDC,
		OpcodeANDD,
		OpcodeANDE,
		OpcodeANDH,
		OpcodeANDL,
		OpcodeANDHL,
		OpcodeANDA,
		OpcodeXORB,
		OpcodeXORC,
		OpcodeXORD,
		OpcodeXORE,
		OpcodeXORH,
		OpcodeXORL,
		OpcodeXORHL,
		OpcodeXORA,
		OpcodeORB,
		OpcodeORC,
		OpcodeORD,
		OpcodeORE,
		OpcodeORH,
		OpcodeORL,
		OpcodeORHL,
		OpcodeORA,
		OpcodeCPB,
		OpcodeCPC,
		OpcodeCPD,
		OpcodeCPE,
		OpcodeCPH,
		OpcodeCPL,
		OpcodeCPHL,
		OpcodeCPA,
		OpcodeRETNZ,
		OpcodePOPBC,
		OpcodeJPNZnn,
		OpcodeJPnn,
		OpcodePUSHBC,
		OpcodeADDn,
		OpcodeRETZ,
		OpcodeRET,
		OpcodeJPZnn,
		OpcodeCB,
		OpcodeCALLnn,
		OpcodeADCn,
		OpcodeRETNC,
		OpcodeRETC,
		OpcodeRETI,
		OpcodeJPCnn,
		OpcodeJPNCnn,
		OpcodeSUBn,
		OpcodeSBCn,
		OpcodeLDHnA,
		OpcodeLDHCA,
		OpcodeANDn,
		OpcodeLDnnA,
		OpcodeXORn,
		OpcodeLDHAn,
		OpcodeLDAnn,
		OpcodeDI,
		OpcodeORn,
		OpcodeEI,
		OpcodeCPn,
	}
}

var _OpcodeMap = map[Opcode]string{
	OpcodeNop:      _OpcodeName[0:3],
	OpcodeLDBCnn:   _OpcodeName[3:9],
	OpcodeINCBC:    _OpcodeName[9:14],
	OpcodeINCB:     _OpcodeName[14:18],
	OpcodeDECB:     _OpcodeName[18:22],
	OpcodeLDBn:     _OpcodeName[22:26],
	OpcodeRLCA:     _OpcodeName[26:30],
	OpcodeADDHLBC:  _OpcodeName[30:37],
	OpcodeLDABC:    _OpcodeName[37:42],
	OpcodeDECBC:    _OpcodeName[42:47],
	OpcodeINCC:     _OpcodeName[47:51],
	OpcodeDECC:     _OpcodeName[51:55],
	OpcodeLDCn:     _OpcodeName[55:59],
	OpcodeRRCA:     _OpcodeName[59:63],
	OpcodeLDDEnn:   _OpcodeName[63:69],
	OpcodeINCDE:    _OpcodeName[69:74],
	OpcodeINCD:     _OpcodeName[74:78],
	OpcodeDECD:     _OpcodeName[78:82],
	OpcodeLDDn:     _OpcodeName[82:86],
	OpcodeRLA:      _OpcodeName[86:89],
	OpcodeJRe:      _OpcodeName[89:92],
	OpcodeADDHLDE:  _OpcodeName[92:99],
	OpcodeLDADE:    _OpcodeName[99:104],
	OpcodeDECDE:    _OpcodeName[104:109],
	OpcodeINCE:     _OpcodeName[109:113],
	OpcodeDECE:     _OpcodeName[113:117],
	OpcodeLDEn:     _OpcodeName[117:121],
	OpcodeRRA:      _OpcodeName[121:124],
	OpcodeJRNZe:    _OpcodeName[124:129],
	OpcodeLDHLnn:   _OpcodeName[129:135],
	OpcodeLDHLAInc: _OpcodeName[135:143],
	OpcodeINCHL:    _OpcodeName[143:148],
	OpcodeINCH:     _OpcodeName[148:152],
	OpcodeDECH:     _OpcodeName[152:156],
	OpcodeLDHn:     _OpcodeName[156:160],
	OpcodeJRZe:     _OpcodeName[160:164],
	OpcodeADDHLHL:  _OpcodeName[164:171],
	OpcodeDECHL:    _OpcodeName[171:176],
	OpcodeINCL:     _OpcodeName[176:180],
	OpcodeDECL:     _OpcodeName[180:184],
	OpcodeLDLn:     _OpcodeName[184:188],
	OpcodeJRNCe:    _OpcodeName[188:193],
	OpcodeLDSPnn:   _OpcodeName[193:199],
	OpcodeLDHLADec: _OpcodeName[199:207],
	OpcodeINCSP:    _OpcodeName[207:212],
	OpcodeJRCe:     _OpcodeName[212:216],
	OpcodeADDHLSP:  _OpcodeName[216:223],
	OpcodeDECSP:    _OpcodeName[223:228],
	OpcodeINCA:     _OpcodeName[228:232],
	OpcodeDECA:     _OpcodeName[232:236],
	OpcodeLDAn:     _OpcodeName[236:240],
	OpcodeLDBB:     _OpcodeName[240:244],
	OpcodeLDBC:     _OpcodeName[244:248],
	OpcodeLDBD:     _OpcodeName[248:252],
	OpcodeLDBE:     _OpcodeName[252:256],
	OpcodeLDBH:     _OpcodeName[256:260],
	OpcodeLDBL:     _OpcodeName[260:264],
	OpcodeLDBHL:    _OpcodeName[264:269],
	OpcodeLDBA:     _OpcodeName[269:273],
	OpcodeLDCB:     _OpcodeName[273:277],
	OpcodeLDCC:     _OpcodeName[277:281],
	OpcodeLDCD:     _OpcodeName[281:285],
	OpcodeLDCE:     _OpcodeName[285:289],
	OpcodeLDCH:     _OpcodeName[289:293],
	OpcodeLDCL:     _OpcodeName[293:297],
	OpcodeLDCHL:    _OpcodeName[297:302],
	OpcodeLDCA:     _OpcodeName[302:306],
	OpcodeLDDB:     _OpcodeName[306:310],
	OpcodeLDDC:     _OpcodeName[310:314],
	OpcodeLDDD:     _OpcodeName[314:318],
	OpcodeLDDE:     _OpcodeName[318:322],
	OpcodeLDDH:     _OpcodeName[322:326],
	OpcodeLDDL:     _OpcodeName[326:330],
	OpcodeLDDHL:    _OpcodeName[330:335],
	OpcodeLDDA:     _OpcodeName[335:339],
	OpcodeLDEB:     _OpcodeName[339:343],
	OpcodeLDEC:     _OpcodeName[343:347],
	OpcodeLDED:     _OpcodeName[347:351],
	OpcodeLDEE:     _OpcodeName[351:355],
	OpcodeLDEH:     _OpcodeName[355:359],
	OpcodeLDEL:     _OpcodeName[359:363],
	OpcodeLDEHL:    _OpcodeName[363:368],
	OpcodeLDEA:     _OpcodeName[368:372],
	OpcodeLDHB:     _OpcodeName[372:376],
	OpcodeLDHC:     _OpcodeName[376:380],
	OpcodeLDHD:     _OpcodeName[380:384],
	OpcodeLDHE:     _OpcodeName[384:388],
	OpcodeLDHH:     _OpcodeName[388:392],
	OpcodeLDHL:     _OpcodeName[392:396],
	OpcodeLDHHL:    _OpcodeName[396:401],
	OpcodeLDHA:     _OpcodeName[401:405],
	OpcodeLDLB:     _OpcodeName[405:409],
	OpcodeLDLC:     _OpcodeName[409:413],
	OpcodeLDLD:     _OpcodeName[413:417],
	OpcodeLDLE:     _OpcodeName[417:421],
	OpcodeLDLH:     _OpcodeName[421:425],
	OpcodeLDLL:     _OpcodeName[425:429],
	OpcodeLDLHL:    _OpcodeName[429:434],
	OpcodeLDLA:     _OpcodeName[434:438],
	OpcodeLDHLB:    _OpcodeName[438:443],
	OpcodeLDHLC:    _OpcodeName[443:448],
	OpcodeLDHLD:    _OpcodeName[448:453],
	OpcodeLDHLE:    _OpcodeName[453:458],
	OpcodeLDHLH:    _OpcodeName[458:463],
	OpcodeLDHLL:    _OpcodeName[463:468],
	OpcodeHALT:     _OpcodeName[468:472],
	OpcodeLDHLA:    _OpcodeName[472:477],
	OpcodeLDAB:     _OpcodeName[477:481],
	OpcodeLDAC:     _OpcodeName[481:485],
	OpcodeLDAD:     _OpcodeName[485:489],
	OpcodeLDAE:     _OpcodeName[489:493],
	OpcodeLDAH:     _OpcodeName[493:497],
	OpcodeLDAL:     _OpcodeName[497:501],
	OpcodeLDAHL:    _OpcodeName[501:506],
	OpcodeLDAA:     _OpcodeName[506:510],
	OpcodeADDB:     _OpcodeName[510:514],
	OpcodeADDC:     _OpcodeName[514:518],
	OpcodeADDD:     _OpcodeName[518:522],
	OpcodeADDE:     _OpcodeName[522:526],
	OpcodeADDH:     _OpcodeName[526:530],
	OpcodeADDL:     _OpcodeName[530:534],
	OpcodeADDHL:    _OpcodeName[534:539],
	OpcodeADDA:     _OpcodeName[539:543],
	OpcodeADCB:     _OpcodeName[543:547],
	OpcodeADCC:     _OpcodeName[547:551],
	OpcodeADCD:     _OpcodeName[551:555],
	OpcodeADCE:     _OpcodeName[555:559],
	OpcodeADCH:     _OpcodeName[559:563],
	OpcodeADCL:     _OpcodeName[563:567],
	OpcodeADCHL:    _OpcodeName[567:572],
	OpcodeADCA:     _OpcodeName[572:576],
	OpcodeSUBB:     _OpcodeName[576:580],
	OpcodeSUBC:     _OpcodeName[580:584],
	OpcodeSUBD:     _OpcodeName[584:588],
	OpcodeSUBE:     _OpcodeName[588:592],
	OpcodeSUBH:     _OpcodeName[592:596],
	OpcodeSUBL:     _OpcodeName[596:600],
	OpcodeSUBHL:    _OpcodeName[600:605],
	OpcodeSUBA:     _OpcodeName[605:609],
	OpcodeSBCB:     _OpcodeName[609:613],
	OpcodeSBCC:     _OpcodeName[613:617],
	OpcodeSBCD:     _OpcodeName[617:621],
	OpcodeSBCE:     _OpcodeName[621:625],
	OpcodeSBCH:     _OpcodeName[625:629],
	OpcodeSBCL:     _OpcodeName[629:633],
	OpcodeSBCHL:    _OpcodeName[633:638],
	OpcodeSBCA:     _OpcodeName[638:642],
	OpcodeANDB:     _OpcodeName[642:646],
	OpcodeANDC:     _OpcodeName[646:650],
	OpcodeANDD:     _OpcodeName[650:654],
	OpcodeANDE:     _OpcodeName[654:658],
	OpcodeANDH:     _OpcodeName[658:662],
	OpcodeANDL:     _OpcodeName[662:666],
	OpcodeANDHL:    _OpcodeName[666:671],
	OpcodeANDA:     _OpcodeName[671:675],
	OpcodeXORB:     _OpcodeName[675:679],
	OpcodeXORC:     _OpcodeName[679:683],
	OpcodeXORD:     _OpcodeName[683:687],
	OpcodeXORE:     _OpcodeName[687:691],
	OpcodeXORH:     _OpcodeName[691:695],
	OpcodeXORL:     _OpcodeName[695:699],
	OpcodeXORHL:    _OpcodeName[699:704],
	OpcodeXORA:     _OpcodeName[704:708],
	OpcodeORB:      _OpcodeName[708:711],
	OpcodeORC:      _OpcodeName[711:714],
	OpcodeORD:      _OpcodeName[714:717],
	OpcodeORE:      _OpcodeName[717:720],
	OpcodeORH:      _OpcodeName[720:723],
	OpcodeORL:      _OpcodeName[723:726],
	OpcodeORHL:     _OpcodeName[726:730],
	OpcodeORA:      _OpcodeName[730:733],
	OpcodeCPB:      _OpcodeName[733:736],
	OpcodeCPC:      _OpcodeName[736:739],
	OpcodeCPD:      _OpcodeName[739:742],
	OpcodeCPE:      _OpcodeName[742:745],
	OpcodeCPH:      _OpcodeName[745:748],
	OpcodeCPL:      _OpcodeName[748:751],
	OpcodeCPHL:     _OpcodeName[751:755],
	OpcodeCPA:      _OpcodeName[755:758],
	OpcodeRETNZ:    _OpcodeName[758:763],
	OpcodePOPBC:    _OpcodeName[763:768],
	OpcodeJPNZnn:   _OpcodeName[768:774],
	OpcodeJPnn:     _OpcodeName[774:778],
	OpcodePUSHBC:   _OpcodeName[778:784],
	OpcodeADDn:     _OpcodeName[784:788],
	OpcodeRETZ:     _OpcodeName[788:792],
	OpcodeRET:      _OpcodeName[792:795],
	OpcodeJPZnn:    _OpcodeName[795:800],
	OpcodeCB:       _OpcodeName[800:802],
	OpcodeCALLnn:   _OpcodeName[802:808],
	OpcodeADCn:     _OpcodeName[808:812],
	OpcodeRETNC:    _OpcodeName[812:817],
	OpcodeRETC:     _OpcodeName[817:821],
	OpcodeRETI:     _OpcodeName[821:825],
	OpcodeJPCnn:    _OpcodeName[825:830],
	OpcodeJPNCnn:   _OpcodeName[830:836],
	OpcodeSUBn:     _OpcodeName[836:840],
	OpcodeSBCn:     _OpcodeName[840:844],
	OpcodeLDHnA:    _OpcodeName[844:849],
	OpcodeLDHCA:    _OpcodeName[849:854],
	OpcodeANDn:     _OpcodeName[854:858],
	OpcodeLDnnA:    _OpcodeName[858:863],
	OpcodeXORn:     _OpcodeName[863:867],
	OpcodeLDHAn:    _OpcodeName[867:872],
	OpcodeLDAnn:    _OpcodeName[872:877],
	OpcodeDI:       _OpcodeName[877:879],
	OpcodeORn:      _OpcodeName[879:882],
	OpcodeEI:       _OpcodeName[882:884],
	OpcodeCPn:      _OpcodeName[884:887],
}

// String implements the Stringer interface.
func (x Opcode) String() string {
	if str, ok := _OpcodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Opcode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Opcode) IsValid() bool {
	_, ok := _OpcodeMap[x]
	return ok
}

var _OpcodeValue = map[string]Opcode{
	_OpcodeName[0:3]:     OpcodeNop,
	_OpcodeName[3:9]:     OpcodeLDBCnn,
	_OpcodeName[9:14]:    OpcodeINCBC,
	_OpcodeName[14:18]:   OpcodeINCB,
	_OpcodeName[18:22]:   OpcodeDECB,
	_OpcodeName[22:26]:   OpcodeLDBn,
	_OpcodeName[26:30]:   OpcodeRLCA,
	_OpcodeName[30:37]:   OpcodeADDHLBC,
	_OpcodeName[37:42]:   OpcodeLDABC,
	_OpcodeName[42:47]:   OpcodeDECBC,
	_OpcodeName[47:51]:   OpcodeINCC,
	_OpcodeName[51:55]:   OpcodeDECC,
	_OpcodeName[55:59]:   OpcodeLDCn,
	_OpcodeName[59:63]:   OpcodeRRCA,
	_OpcodeName[63:69]:   OpcodeLDDEnn,
	_OpcodeName[69:74]:   OpcodeINCDE,
	_OpcodeName[74:78]:   OpcodeINCD,
	_OpcodeName[78:82]:   OpcodeDECD,
	_OpcodeName[82:86]:   OpcodeLDDn,
	_OpcodeName[86:89]:   OpcodeRLA,
	_OpcodeName[89:92]:   OpcodeJRe,
	_OpcodeName[92:99]:   OpcodeADDHLDE,
	_OpcodeName[99:104]:  OpcodeLDADE,
	_OpcodeName[104:109]: OpcodeDECDE,
	_OpcodeName[109:113]: OpcodeINCE,
	_OpcodeName[113:117]: OpcodeDECE,
	_OpcodeName[117:121]: OpcodeLDEn,
	_OpcodeName[121:124]: OpcodeRRA,
	_OpcodeName[124:129]: OpcodeJRNZe,
	_OpcodeName[129:135]: OpcodeLDHLnn,
	_OpcodeName[135:143]: OpcodeLDHLAInc,
	_OpcodeName[143:148]: OpcodeINCHL,
	_OpcodeName[148:152]: OpcodeINCH,
	_OpcodeName[152:156]: OpcodeDECH,
	_OpcodeName[156:160]: OpcodeLDHn,
	_OpcodeName[160:164]: OpcodeJRZe,
	_OpcodeName[164:171]: OpcodeADDHLHL,
	_OpcodeName[171:176]: OpcodeDECHL,
	_OpcodeName[176:180]: OpcodeINCL,
	_OpcodeName[180:184]: OpcodeDECL,
	_OpcodeName[184:188]: OpcodeLDLn,
	_OpcodeName[188:193]: OpcodeJRNCe,
	_OpcodeName[193:199]: OpcodeLDSPnn,
	_OpcodeName[199:207]: OpcodeLDHLADec,
	_OpcodeName[207:212]: OpcodeINCSP,
	_OpcodeName[212:216]: OpcodeJRCe,
	_OpcodeName[216:223]: OpcodeADDHLSP,
	_OpcodeName[223:228]: OpcodeDECSP,
	_OpcodeName[228:232]: OpcodeINCA,
	_OpcodeName[232:236]: OpcodeDECA,
	_OpcodeName[236:240]: OpcodeLDAn,
	_OpcodeName[240:244]: OpcodeLDBB,
	_OpcodeName[244:248]: OpcodeLDBC,
	_OpcodeName[248:252]: OpcodeLDBD,
	_OpcodeName[252:256]: OpcodeLDBE,
	_OpcodeName[256:260]: OpcodeLDBH,
	_OpcodeName[260:264]: OpcodeLDBL,
	_OpcodeName[264:269]: OpcodeLDBHL,
	_OpcodeName[269:273]: OpcodeLDBA,
	_OpcodeName[273:277]: OpcodeLDCB,
	_OpcodeName[277:281]: OpcodeLDCC,
	_OpcodeName[281:285]: OpcodeLDCD,
	_OpcodeName[285:289]: OpcodeLDCE,
	_OpcodeName[289:293]: OpcodeLDCH,
	_OpcodeName[293:297]: OpcodeLDCL,
	_OpcodeName[297:302]: OpcodeLDCHL,
	_OpcodeName[302:306]: OpcodeLDCA,
	_OpcodeName[306:310]: OpcodeLDDB,
	_OpcodeName[310:314]: OpcodeLDDC,
	_OpcodeName[314:318]: OpcodeLDDD,
	_OpcodeName[318:322]: OpcodeLDDE,
	_OpcodeName[322:326]: OpcodeLDDH,
	_OpcodeName[326:330]: OpcodeLDDL,
	_OpcodeName[330:335]: OpcodeLDDHL,
	_OpcodeName[335:339]: OpcodeLDDA,
	_OpcodeName[339:343]: OpcodeLDEB,
	_OpcodeName[343:347]: OpcodeLDEC,
	_OpcodeName[347:351]: OpcodeLDED,
	_OpcodeName[351:355]: OpcodeLDEE,
	_OpcodeName[355:359]: OpcodeLDEH,
	_OpcodeName[359:363]: OpcodeLDEL,
	_OpcodeName[363:368]: OpcodeLDEHL,
	_OpcodeName[368:372]: OpcodeLDEA,
	_OpcodeName[372:376]: OpcodeLDHB,
	_OpcodeName[376:380]: OpcodeLDHC,
	_OpcodeName[380:384]: OpcodeLDHD,
	_OpcodeName[384:388]: OpcodeLDHE,
	_OpcodeName[388:392]: OpcodeLDHH,
	_OpcodeName[392:396]: OpcodeLDHL,
	_OpcodeName[396:401]: OpcodeLDHHL,
	_OpcodeName[401:405]: OpcodeLDHA,
	_OpcodeName[405:409]: OpcodeLDLB,
	_OpcodeName[409:413]: OpcodeLDLC,
	_OpcodeName[413:417]: OpcodeLDLD,
	_OpcodeName[417:421]: OpcodeLDLE,
	_OpcodeName[421:425]: OpcodeLDLH,
	_OpcodeName[425:429]: OpcodeLDLL,
	_OpcodeName[429:434]: OpcodeLDLHL,
	_OpcodeName[434:438]: OpcodeLDLA,
	_OpcodeName[438:443]: OpcodeLDHLB,
	_OpcodeName[443:448]: OpcodeLDHLC,
	_OpcodeName[448:453]: OpcodeLDHLD,
	_OpcodeName[453:458]: OpcodeLDHLE,
	_OpcodeName[458:463]: OpcodeLDHLH,
	_OpcodeName[463:468]: OpcodeLDHLL,
	_OpcodeName[468:472]: OpcodeHALT,
	_OpcodeName[472:477]: OpcodeLDHLA,
	_OpcodeName[477:481]: OpcodeLDAB,
	_OpcodeName[481:485]: OpcodeLDAC,
	_OpcodeName[485:489]: OpcodeLDAD,
	_OpcodeName[489:493]: OpcodeLDAE,
	_OpcodeName[493:497]: OpcodeLDAH,
	_OpcodeName[497:501]: OpcodeLDAL,
	_OpcodeName[501:506]: OpcodeLDAHL,
	_OpcodeName[506:510]: OpcodeLDAA,
	_OpcodeName[510:514]: OpcodeADDB,
	_OpcodeName[514:518]: OpcodeADDC,
	_OpcodeName[518:522]: OpcodeADDD,
	_OpcodeName[522:526]: OpcodeADDE,
	_OpcodeName[526:530]: OpcodeADDH,
	_OpcodeName[530:534]: OpcodeADDL,
	_OpcodeName[534:539]: OpcodeADDHL,
	_OpcodeName[539:543]: OpcodeADDA,
	_OpcodeName[543:547]: OpcodeADCB,
	_OpcodeName[547:551]: OpcodeADCC,
	_OpcodeName[551:555]: OpcodeADCD,
	_OpcodeName[555:559]: OpcodeADCE,
	_OpcodeName[559:563]: OpcodeADCH,
	_OpcodeName[563:567]: OpcodeADCL,
	_OpcodeName[567:572]: OpcodeADCHL,
	_OpcodeName[572:576]: OpcodeADCA,
	_OpcodeName[576:580]: OpcodeSUBB,
	_OpcodeName[580:584]: OpcodeSUBC,
	_OpcodeName[584:588]: OpcodeSUBD,
	_OpcodeName[588:592]: OpcodeSUBE,
	_OpcodeName[592:596]: OpcodeSUBH,
	_OpcodeName[596:600]: OpcodeSUBL,
	_OpcodeName[600:605]: OpcodeSUBHL,
	_OpcodeName[605:609]: OpcodeSUBA,
	_OpcodeName[609:613]: OpcodeSBCB,
	_OpcodeName[613:617]: OpcodeSBCC,
	_OpcodeName[617:621]: OpcodeSBCD,
	_OpcodeName[621:625]: OpcodeSBCE,
	_OpcodeName[625:629]: OpcodeSBCH,
	_OpcodeName[629:633]: OpcodeSBCL,
	_OpcodeName[633:638]: OpcodeSBCHL,
	_OpcodeName[638:642]: OpcodeSBCA,
	_OpcodeName[642:646]: OpcodeANDB,
	_OpcodeName[646:650]: OpcodeANDC,
	_OpcodeName[650:654]: OpcodeANDD,
	_OpcodeName[654:658]: OpcodeANDE,
	_OpcodeName[658:662]: OpcodeANDH,
	_OpcodeName[662:666]: OpcodeANDL,
	_OpcodeName[666:671]: OpcodeANDHL,
	_OpcodeName[671:675]: OpcodeANDA,
	_OpcodeName[675:679]: OpcodeXORB,
	_OpcodeName[679:683]: OpcodeXORC,
	_OpcodeName[683:687]: OpcodeXORD,
	_OpcodeName[687:691]: OpcodeXORE,
	_OpcodeName[691:695]: OpcodeXORH,
	_OpcodeName[695:699]: OpcodeXORL,
	_OpcodeName[699:704]: OpcodeXORHL,
	_OpcodeName[704:708]: OpcodeXORA,
	_OpcodeName[708:711]: OpcodeORB,
	_OpcodeName[711:714]: OpcodeORC,
	_OpcodeName[714:717]: OpcodeORD,
	_OpcodeName[717:720]: OpcodeORE,
	_OpcodeName[720:723]: OpcodeORH,
	_OpcodeName[723:726]: OpcodeORL,
	_OpcodeName[726:730]: OpcodeORHL,
	_OpcodeName[730:733]: OpcodeORA,
	_OpcodeName[733:736]: OpcodeCPB,
	_OpcodeName[736:739]: OpcodeCPC,
	_OpcodeName[739:742]: OpcodeCPD,
	_OpcodeName[742:745]: OpcodeCPE,
	_OpcodeName[745:748]: OpcodeCPH,
	_OpcodeName[748:751]: OpcodeCPL,
	_OpcodeName[751:755]: OpcodeCPHL,
	_OpcodeName[755:758]: OpcodeCPA,
	_OpcodeName[758:763]: OpcodeRETNZ,
	_OpcodeName[763:768]: OpcodePOPBC,
	_OpcodeName[768:774]: OpcodeJPNZnn,
	_OpcodeName[774:778]: OpcodeJPnn,
	_OpcodeName[778:784]: OpcodePUSHBC,
	_OpcodeName[784:788]: OpcodeADDn,
	_OpcodeName[788:792]: OpcodeRETZ,
	_OpcodeName[792:795]: OpcodeRET,
	_OpcodeName[795:800]: OpcodeJPZnn,
	_OpcodeName[800:802]: OpcodeCB,
	_OpcodeName[802:808]: OpcodeCALLnn,
	_OpcodeName[808:812]: OpcodeADCn,
	_OpcodeName[812:817]: OpcodeRETNC,
	_OpcodeName[817:821]: OpcodeRETC,
	_OpcodeName[821:825]: OpcodeRETI,
	_OpcodeName[825:830]: OpcodeJPCnn,
	_OpcodeName[830:836]: OpcodeJPNCnn,
	_OpcodeName[836:840]: OpcodeSUBn,
	_OpcodeName[840:844]: OpcodeSBCn,
	_OpcodeName[844:849]: OpcodeLDHnA,
	_OpcodeName[849:854]: OpcodeLDHCA,
	_OpcodeName[854:858]: OpcodeANDn,
	_OpcodeName[858:863]: OpcodeLDnnA,
	_OpcodeName[863:867]: OpcodeXORn,
	_OpcodeName[867:872]: OpcodeLDHAn,
	_OpcodeName[872:877]: OpcodeLDAnn,
	_OpcodeName[877:879]: OpcodeDI,
	_OpcodeName[879:882]: OpcodeORn,
	_OpcodeName[882:884]: OpcodeEI,
	_OpcodeName[884:887]: OpcodeCPn,
}

// ParseOpcode attempts to convert a string to a Opcode.
func ParseOpcode(name string) (Opcode, error) {
	if x, ok := _OpcodeValue[name]; ok {
		return x, nil
	}
	return Opcode(0), fmt.Errorf("%s is %w", name, ErrInvalidOpcode)
}

// MarshalText implements the text marshaller method.
func (x Opcode) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Opcode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOpcode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Set implements the Golang flag.Value interface func.
func (x *Opcode) Set(val string) error {
	v, err := ParseOpcode(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *Opcode) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *Opcode) Type() string {
	return "Opcode"
}

const (
	CbRLC cb = iota
	CbRRC
	CbRL
	CbRR
	CbSLA
	CbSRA
	CbSWAP
	CbSRL
	CbBit0
	CbBit1
	CbBit2
	CbBit3
	CbBit4
	CbBit5
	CbBit6
	CbBit7
	CbRes0
	CbRes1
	CbRes2
	CbRes3
	CbRes4
	CbRes5
	CbRes6
	CbRes7
	CbSet0
	CbSet1
	CbSet2
	CbSet3
	CbSet4
	CbSet5
	CbSet6
	CbSet7
)

var ErrInvalidcb = errors.New("not a valid cb")

const _cbName = "RLCRRCRLRRSLASRASWAPSRLBit0Bit1Bit2Bit3Bit4Bit5Bit6Bit7Res0Res1Res2Res3Res4Res5Res6Res7Set0Set1Set2Set3Set4Set5Set6Set7"

// cbValues returns a list of the values for cb
func cbValues() []cb {
	return []cb{
		CbRLC,
		CbRRC,
		CbRL,
		CbRR,
		CbSLA,
		CbSRA,
		CbSWAP,
		CbSRL,
		CbBit0,
		CbBit1,
		CbBit2,
		CbBit3,
		CbBit4,
		CbBit5,
		CbBit6,
		CbBit7,
		CbRes0,
		CbRes1,
		CbRes2,
		CbRes3,
		CbRes4,
		CbRes5,
		CbRes6,
		CbRes7,
		CbSet0,
		CbSet1,
		CbSet2,
		CbSet3,
		CbSet4,
		CbSet5,
		CbSet6,
		CbSet7,
	}
}

var _cbMap = map[cb]string{
	CbRLC:  _cbName[0:3],
	CbRRC:  _cbName[3:6],
	CbRL:   _cbName[6:8],
	CbRR:   _cbName[8:10],
	CbSLA:  _cbName[10:13],
	CbSRA:  _cbName[13:16],
	CbSWAP: _cbName[16:20],
	CbSRL:  _cbName[20:23],
	CbBit0: _cbName[23:27],
	CbBit1: _cbName[27:31],
	CbBit2: _cbName[31:35],
	CbBit3: _cbName[35:39],
	CbBit4: _cbName[39:43],
	CbBit5: _cbName[43:47],
	CbBit6: _cbName[47:51],
	CbBit7: _cbName[51:55],
	CbRes0: _cbName[55:59],
	CbRes1: _cbName[59:63],
	CbRes2: _cbName[63:67],
	CbRes3: _cbName[67:71],
	CbRes4: _cbName[71:75],
	CbRes5: _cbName[75:79],
	CbRes6: _cbName[79:83],
	CbRes7: _cbName[83:87],
	CbSet0: _cbName[87:91],
	CbSet1: _cbName[91:95],
	CbSet2: _cbName[95:99],
	CbSet3: _cbName[99:103],
	CbSet4: _cbName[103:107],
	CbSet5: _cbName[107:111],
	CbSet6: _cbName[111:115],
	CbSet7: _cbName[115:119],
}

// String implements the Stringer interface.
func (x cb) String() string {
	if str, ok := _cbMap[x]; ok {
		return str
	}
	return fmt.Sprintf("cb(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x cb) IsValid() bool {
	_, ok := _cbMap[x]
	return ok
}

var _cbValue = map[string]cb{
	_cbName[0:3]:     CbRLC,
	_cbName[3:6]:     CbRRC,
	_cbName[6:8]:     CbRL,
	_cbName[8:10]:    CbRR,
	_cbName[10:13]:   CbSLA,
	_cbName[13:16]:   CbSRA,
	_cbName[16:20]:   CbSWAP,
	_cbName[20:23]:   CbSRL,
	_cbName[23:27]:   CbBit0,
	_cbName[27:31]:   CbBit1,
	_cbName[31:35]:   CbBit2,
	_cbName[35:39]:   CbBit3,
	_cbName[39:43]:   CbBit4,
	_cbName[43:47]:   CbBit5,
	_cbName[47:51]:   CbBit6,
	_cbName[51:55]:   CbBit7,
	_cbName[55:59]:   CbRes0,
	_cbName[59:63]:   CbRes1,
	_cbName[63:67]:   CbRes2,
	_cbName[67:71]:   CbRes3,
	_cbName[71:75]:   CbRes4,
	_cbName[75:79]:   CbRes5,
	_cbName[79:83]:   CbRes6,
	_cbName[83:87]:   CbRes7,
	_cbName[87:91]:   CbSet0,
	_cbName[91:95]:   CbSet1,
	_cbName[95:99]:   CbSet2,
	_cbName[99:103]:  CbSet3,
	_cbName[103:107]: CbSet4,
	_cbName[107:111]: CbSet5,
	_cbName[111:115]: CbSet6,
	_cbName[115:119]: CbSet7,
}

// Parsecb attempts to convert a string to a cb.
func Parsecb(name string) (cb, error) {
	if x, ok := _cbValue[name]; ok {
		return x, nil
	}
	return cb(0), fmt.Errorf("%s is %w", name, ErrInvalidcb)
}

// MarshalText implements the text marshaller method.
func (x cb) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *cb) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := Parsecb(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Set implements the Golang flag.Value interface func.
func (x *cb) Set(val string) error {
	v, err := Parsecb(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *cb) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *cb) Type() string {
	return "cb"
}
