// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.0
// Revision: 4061a5d82779342c5863a515363feb943fa59455
// Build Date: 2025-07-22T03:42:20Z
// Built By: goreleaser

package model

import (
	"errors"
	"fmt"
)

const (
	AddrZero                 Addr = 0
	AddrBootROMEnd           Addr = 255
	AddrCartridgeEntryPoint  Addr = 256
	AddrNintendoLogoBegin    Addr = 260
	AddrNintendoLogoEnd      Addr = 307
	AddrTitleBegin           Addr = 308
	AddrTitleEnd             Addr = 323
	AddrNewLicenseeCodeBegin Addr = 324
	AddrNewLicenseeCodeEnd   Addr = 325
	AddrSGBFlag              Addr = 326
	AddrCartridgeType        Addr = 327
	AddrROMSize              Addr = 328
	AddrRAMSize              Addr = 329
	AddrDestCode             Addr = 330
	AddrOldLicenseeCode      Addr = 331
	AddrMaskROMVersionNo     Addr = 332
	AddrHeaderChecksum       Addr = 333
	AddrGlobalChecksumBegin  Addr = 334
	AddrGlobalChecksumEnd    Addr = 335
	AddrCartridgeBank0End    Addr = 16383
	AddrCartridgeBankNBegin  Addr = 16384
	AddrCartridgeBankNEnd    Addr = 32767
	AddrTileDataBegin        Addr = 32768
	AddrTileDataEnd          Addr = 38911
	AddrTileMap0Begin        Addr = 38912
	AddrTileMap0End          Addr = 39935
	AddrTileMap1Begin        Addr = 39936
	AddrTileMap1End          Addr = 40959
	AddrCartridgeRAMBegin    Addr = 40960
	AddrCartridgeRAMEnd      Addr = 49151
	AddrWRAMBegin            Addr = 49152
	AddrWRAMEnd              Addr = 57343
	AddrEchoRAMBegin         Addr = 57344
	AddrEchoRAMEnd           Addr = 65023
	AddrOAMBegin             Addr = 65024
	AddrOAMEnd               Addr = 65183
	AddrProhibitedBegin      Addr = 65184
	AddrProhibitedEnd        Addr = 65279
	AddrP1                   Addr = 65280
	AddrSB                   Addr = 65281
	AddrSC                   Addr = 65282
	AddrDIV                  Addr = 65284
	AddrTIMA                 Addr = 65285
	AddrTMA                  Addr = 65286
	AddrTAC                  Addr = 65287
	AddrIF                   Addr = 65295
	AddrLCDC                 Addr = 65344
	AddrSTAT                 Addr = 65345
	AddrSCY                  Addr = 65346
	AddrSCX                  Addr = 65347
	AddrLY                   Addr = 65348
	AddrLYC                  Addr = 65349
	AddrDMA                  Addr = 65350
	AddrBGP                  Addr = 65351
	AddrOBP0                 Addr = 65352
	AddrOBP1                 Addr = 65353
	AddrWY                   Addr = 65354
	AddrWX                   Addr = 65355
	AddrNR10                 Addr = 65296
	AddrNR11                 Addr = 65297
	AddrNR12                 Addr = 65298
	AddrNR13                 Addr = 65299
	AddrNR14                 Addr = 65300
	AddrNR21                 Addr = 65302
	AddrNR22                 Addr = 65303
	AddrNR23                 Addr = 65304
	AddrNR24                 Addr = 65305
	AddrNR30                 Addr = 65306
	AddrNR31                 Addr = 65307
	AddrNR32                 Addr = 65308
	AddrNR33                 Addr = 65309
	AddrNR34                 Addr = 65310
	AddrNR41                 Addr = 65312
	AddrNR42                 Addr = 65313
	AddrNR43                 Addr = 65314
	AddrNR44                 Addr = 65315
	AddrNR50                 Addr = 65316
	AddrNR51                 Addr = 65317
	AddrNR52                 Addr = 65318
	AddrWaveRAMBegin         Addr = 65328
	AddrWaveRAMEnd           Addr = 65343
	AddrBootROMLock          Addr = 65360
	AddrHRAMBegin            Addr = 65408
	AddrHRAMEnd              Addr = 65534
	AddrIE                   Addr = 65535
)

var ErrInvalidAddr = errors.New("not a valid Addr")

const _AddrName = "ZeroBootROMEndCartridgeEntryPointNintendoLogoBeginNintendoLogoEndTitleBeginTitleEndNewLicenseeCodeBeginNewLicenseeCodeEndSGBFlagCartridgeTypeROMSizeRAMSizeDestCodeOldLicenseeCodeMaskROMVersionNoHeaderChecksumGlobalChecksumBeginGlobalChecksumEndCartridgeBank0EndCartridgeBankNBeginCartridgeBankNEndTileDataBeginTileDataEndTileMap0BeginTileMap0EndTileMap1BeginTileMap1EndCartridgeRAMBeginCartridgeRAMEndWRAMBeginWRAMEndEchoRAMBeginEchoRAMEndOAMBeginOAMEndProhibitedBeginProhibitedEndP1SBSCDIVTIMATMATACIFLCDCSTATSCYSCXLYLYCDMABGPOBP0OBP1WYWXNR10NR11NR12NR13NR14NR21NR22NR23NR24NR30NR31NR32NR33NR34NR41NR42NR43NR44NR50NR51NR52WaveRAMBeginWaveRAMEndBootROMLockHRAMBeginHRAMEndIE"

var _AddrMap = map[Addr]string{
	AddrZero:                 _AddrName[0:4],
	AddrBootROMEnd:           _AddrName[4:14],
	AddrCartridgeEntryPoint:  _AddrName[14:33],
	AddrNintendoLogoBegin:    _AddrName[33:50],
	AddrNintendoLogoEnd:      _AddrName[50:65],
	AddrTitleBegin:           _AddrName[65:75],
	AddrTitleEnd:             _AddrName[75:83],
	AddrNewLicenseeCodeBegin: _AddrName[83:103],
	AddrNewLicenseeCodeEnd:   _AddrName[103:121],
	AddrSGBFlag:              _AddrName[121:128],
	AddrCartridgeType:        _AddrName[128:141],
	AddrROMSize:              _AddrName[141:148],
	AddrRAMSize:              _AddrName[148:155],
	AddrDestCode:             _AddrName[155:163],
	AddrOldLicenseeCode:      _AddrName[163:178],
	AddrMaskROMVersionNo:     _AddrName[178:194],
	AddrHeaderChecksum:       _AddrName[194:208],
	AddrGlobalChecksumBegin:  _AddrName[208:227],
	AddrGlobalChecksumEnd:    _AddrName[227:244],
	AddrCartridgeBank0End:    _AddrName[244:261],
	AddrCartridgeBankNBegin:  _AddrName[261:280],
	AddrCartridgeBankNEnd:    _AddrName[280:297],
	AddrTileDataBegin:        _AddrName[297:310],
	AddrTileDataEnd:          _AddrName[310:321],
	AddrTileMap0Begin:        _AddrName[321:334],
	AddrTileMap0End:          _AddrName[334:345],
	AddrTileMap1Begin:        _AddrName[345:358],
	AddrTileMap1End:          _AddrName[358:369],
	AddrCartridgeRAMBegin:    _AddrName[369:386],
	AddrCartridgeRAMEnd:      _AddrName[386:401],
	AddrWRAMBegin:            _AddrName[401:410],
	AddrWRAMEnd:              _AddrName[410:417],
	AddrEchoRAMBegin:         _AddrName[417:429],
	AddrEchoRAMEnd:           _AddrName[429:439],
	AddrOAMBegin:             _AddrName[439:447],
	AddrOAMEnd:               _AddrName[447:453],
	AddrProhibitedBegin:      _AddrName[453:468],
	AddrProhibitedEnd:        _AddrName[468:481],
	AddrP1:                   _AddrName[481:483],
	AddrSB:                   _AddrName[483:485],
	AddrSC:                   _AddrName[485:487],
	AddrDIV:                  _AddrName[487:490],
	AddrTIMA:                 _AddrName[490:494],
	AddrTMA:                  _AddrName[494:497],
	AddrTAC:                  _AddrName[497:500],
	AddrIF:                   _AddrName[500:502],
	AddrLCDC:                 _AddrName[502:506],
	AddrSTAT:                 _AddrName[506:510],
	AddrSCY:                  _AddrName[510:513],
	AddrSCX:                  _AddrName[513:516],
	AddrLY:                   _AddrName[516:518],
	AddrLYC:                  _AddrName[518:521],
	AddrDMA:                  _AddrName[521:524],
	AddrBGP:                  _AddrName[524:527],
	AddrOBP0:                 _AddrName[527:531],
	AddrOBP1:                 _AddrName[531:535],
	AddrWY:                   _AddrName[535:537],
	AddrWX:                   _AddrName[537:539],
	AddrNR10:                 _AddrName[539:543],
	AddrNR11:                 _AddrName[543:547],
	AddrNR12:                 _AddrName[547:551],
	AddrNR13:                 _AddrName[551:555],
	AddrNR14:                 _AddrName[555:559],
	AddrNR21:                 _AddrName[559:563],
	AddrNR22:                 _AddrName[563:567],
	AddrNR23:                 _AddrName[567:571],
	AddrNR24:                 _AddrName[571:575],
	AddrNR30:                 _AddrName[575:579],
	AddrNR31:                 _AddrName[579:583],
	AddrNR32:                 _AddrName[583:587],
	AddrNR33:                 _AddrName[587:591],
	AddrNR34:                 _AddrName[591:595],
	AddrNR41:                 _AddrName[595:599],
	AddrNR42:                 _AddrName[599:603],
	AddrNR43:                 _AddrName[603:607],
	AddrNR44:                 _AddrName[607:611],
	AddrNR50:                 _AddrName[611:615],
	AddrNR51:                 _AddrName[615:619],
	AddrNR52:                 _AddrName[619:623],
	AddrWaveRAMBegin:         _AddrName[623:635],
	AddrWaveRAMEnd:           _AddrName[635:645],
	AddrBootROMLock:          _AddrName[645:656],
	AddrHRAMBegin:            _AddrName[656:665],
	AddrHRAMEnd:              _AddrName[665:672],
	AddrIE:                   _AddrName[672:674],
}

// String implements the Stringer interface.
func (x Addr) String() string {
	if str, ok := _AddrMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Addr(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Addr) IsValid() bool {
	_, ok := _AddrMap[x]
	return ok
}

var _AddrValue = map[string]Addr{
	_AddrName[0:4]:     AddrZero,
	_AddrName[4:14]:    AddrBootROMEnd,
	_AddrName[14:33]:   AddrCartridgeEntryPoint,
	_AddrName[33:50]:   AddrNintendoLogoBegin,
	_AddrName[50:65]:   AddrNintendoLogoEnd,
	_AddrName[65:75]:   AddrTitleBegin,
	_AddrName[75:83]:   AddrTitleEnd,
	_AddrName[83:103]:  AddrNewLicenseeCodeBegin,
	_AddrName[103:121]: AddrNewLicenseeCodeEnd,
	_AddrName[121:128]: AddrSGBFlag,
	_AddrName[128:141]: AddrCartridgeType,
	_AddrName[141:148]: AddrROMSize,
	_AddrName[148:155]: AddrRAMSize,
	_AddrName[155:163]: AddrDestCode,
	_AddrName[163:178]: AddrOldLicenseeCode,
	_AddrName[178:194]: AddrMaskROMVersionNo,
	_AddrName[194:208]: AddrHeaderChecksum,
	_AddrName[208:227]: AddrGlobalChecksumBegin,
	_AddrName[227:244]: AddrGlobalChecksumEnd,
	_AddrName[244:261]: AddrCartridgeBank0End,
	_AddrName[261:280]: AddrCartridgeBankNBegin,
	_AddrName[280:297]: AddrCartridgeBankNEnd,
	_AddrName[297:310]: AddrTileDataBegin,
	_AddrName[310:321]: AddrTileDataEnd,
	_AddrName[321:334]: AddrTileMap0Begin,
	_AddrName[334:345]: AddrTileMap0End,
	_AddrName[345:358]: AddrTileMap1Begin,
	_AddrName[358:369]: AddrTileMap1End,
	_AddrName[369:386]: AddrCartridgeRAMBegin,
	_AddrName[386:401]: AddrCartridgeRAMEnd,
	_AddrName[401:410]: AddrWRAMBegin,
	_AddrName[410:417]: AddrWRAMEnd,
	_AddrName[417:429]: AddrEchoRAMBegin,
	_AddrName[429:439]: AddrEchoRAMEnd,
	_AddrName[439:447]: AddrOAMBegin,
	_AddrName[447:453]: AddrOAMEnd,
	_AddrName[453:468]: AddrProhibitedBegin,
	_AddrName[468:481]: AddrProhibitedEnd,
	_AddrName[481:483]: AddrP1,
	_AddrName[483:485]: AddrSB,
	_AddrName[485:487]: AddrSC,
	_AddrName[487:490]: AddrDIV,
	_AddrName[490:494]: AddrTIMA,
	_AddrName[494:497]: AddrTMA,
	_AddrName[497:500]: AddrTAC,
	_AddrName[500:502]: AddrIF,
	_AddrName[502:506]: AddrLCDC,
	_AddrName[506:510]: AddrSTAT,
	_AddrName[510:513]: AddrSCY,
	_AddrName[513:516]: AddrSCX,
	_AddrName[516:518]: AddrLY,
	_AddrName[518:521]: AddrLYC,
	_AddrName[521:524]: AddrDMA,
	_AddrName[524:527]: AddrBGP,
	_AddrName[527:531]: AddrOBP0,
	_AddrName[531:535]: AddrOBP1,
	_AddrName[535:537]: AddrWY,
	_AddrName[537:539]: AddrWX,
	_AddrName[539:543]: AddrNR10,
	_AddrName[543:547]: AddrNR11,
	_AddrName[547:551]: AddrNR12,
	_AddrName[551:555]: AddrNR13,
	_AddrName[555:559]: AddrNR14,
	_AddrName[559:563]: AddrNR21,
	_AddrName[563:567]: AddrNR22,
	_AddrName[567:571]: AddrNR23,
	_AddrName[571:575]: AddrNR24,
	_AddrName[575:579]: AddrNR30,
	_AddrName[579:583]: AddrNR31,
	_AddrName[583:587]: AddrNR32,
	_AddrName[587:591]: AddrNR33,
	_AddrName[591:595]: AddrNR34,
	_AddrName[595:599]: AddrNR41,
	_AddrName[599:603]: AddrNR42,
	_AddrName[603:607]: AddrNR43,
	_AddrName[607:611]: AddrNR44,
	_AddrName[611:615]: AddrNR50,
	_AddrName[615:619]: AddrNR51,
	_AddrName[619:623]: AddrNR52,
	_AddrName[623:635]: AddrWaveRAMBegin,
	_AddrName[635:645]: AddrWaveRAMEnd,
	_AddrName[645:656]: AddrBootROMLock,
	_AddrName[656:665]: AddrHRAMBegin,
	_AddrName[665:672]: AddrHRAMEnd,
	_AddrName[672:674]: AddrIE,
}

// ParseAddr attempts to convert a string to a Addr.
func ParseAddr(name string) (Addr, error) {
	if x, ok := _AddrValue[name]; ok {
		return x, nil
	}
	return Addr(0), fmt.Errorf("%s is %w", name, ErrInvalidAddr)
}

// Set implements the Golang flag.Value interface func.
func (x *Addr) Set(val string) error {
	v, err := ParseAddr(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *Addr) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *Addr) Type() string {
	return "Addr"
}
