// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package gui

import (
	"errors"
	"fmt"
)

const (
	SOCDResolutionUnfiltered SOCDResolution = iota
	SOCDResolutionOppositeNeutral
	SOCDResolutionFirstWinsSecondDisabled
	SOCDResolutionOppositeNeutralFirstDisabled
)

var ErrInvalidSOCDResolution = errors.New("not a valid SOCDResolution")

const _SOCDResolutionName = "UnfilteredOppositeNeutralFirstWinsSecondDisabledOppositeNeutralFirstDisabled"

// SOCDResolutionValues returns a list of the values for SOCDResolution
func SOCDResolutionValues() []SOCDResolution {
	return []SOCDResolution{
		SOCDResolutionUnfiltered,
		SOCDResolutionOppositeNeutral,
		SOCDResolutionFirstWinsSecondDisabled,
		SOCDResolutionOppositeNeutralFirstDisabled,
	}
}

var _SOCDResolutionMap = map[SOCDResolution]string{
	SOCDResolutionUnfiltered:                   _SOCDResolutionName[0:10],
	SOCDResolutionOppositeNeutral:              _SOCDResolutionName[10:25],
	SOCDResolutionFirstWinsSecondDisabled:      _SOCDResolutionName[25:48],
	SOCDResolutionOppositeNeutralFirstDisabled: _SOCDResolutionName[48:76],
}

// String implements the Stringer interface.
func (x SOCDResolution) String() string {
	if str, ok := _SOCDResolutionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SOCDResolution(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SOCDResolution) IsValid() bool {
	_, ok := _SOCDResolutionMap[x]
	return ok
}

var _SOCDResolutionValue = map[string]SOCDResolution{
	_SOCDResolutionName[0:10]:  SOCDResolutionUnfiltered,
	_SOCDResolutionName[10:25]: SOCDResolutionOppositeNeutral,
	_SOCDResolutionName[25:48]: SOCDResolutionFirstWinsSecondDisabled,
	_SOCDResolutionName[48:76]: SOCDResolutionOppositeNeutralFirstDisabled,
}

// ParseSOCDResolution attempts to convert a string to a SOCDResolution.
func ParseSOCDResolution(name string) (SOCDResolution, error) {
	if x, ok := _SOCDResolutionValue[name]; ok {
		return x, nil
	}
	return SOCDResolution(0), fmt.Errorf("%s is %w", name, ErrInvalidSOCDResolution)
}

// MarshalText implements the text marshaller method.
func (x SOCDResolution) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SOCDResolution) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSOCDResolution(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Set implements the Golang flag.Value interface func.
func (x *SOCDResolution) Set(val string) error {
	v, err := ParseSOCDResolution(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *SOCDResolution) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *SOCDResolution) Type() string {
	return "SOCDResolution"
}
