// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetCoreDump():Promise<model.CoreDump>;

export function GetSpeedPct():Promise<string>;

export function SetKeyState(arg1:Record<string, boolean>):Promise<void>;

export function StartGB():Promise<void>;

export function StartWebSocketServer():Promise<void>;
