// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function Load():Promise<void>;

export function MachineStateRequest(arg1:main.MachineStateRequest):Promise<void>;

export function Pause():Promise<void>;

export function RequestExecutionLog():Promise<void>;

export function Save():Promise<void>;

export function SetKeyState(arg1:Record<string, boolean>):Promise<void>;

export function Start():Promise<void>;

export function Step():Promise<void>;
