// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function MachineStateRequest(arg1) {
  return window['go']['main']['App']['MachineStateRequest'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Save() {
  return window['go']['main']['App']['Save']();
}

export function SetKeyState(arg1) {
  return window['go']['main']['App']['SetKeyState'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Step() {
  return window['go']['main']['App']['Step']();
}
