// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCoreDump() {
  return window['go']['main']['App']['GetCoreDump']();
}

export function GetSpeedPct() {
  return window['go']['main']['App']['GetSpeedPct']();
}

export function SetKeyState(arg1) {
  return window['go']['main']['App']['SetKeyState'](arg1);
}

export function StartGB() {
  return window['go']['main']['App']['StartGB']();
}

export function StartWebSocketServer() {
  return window['go']['main']['App']['StartWebSocketServer']();
}
